### ISSUE TITLE
Table already exists error fails query installing multiple modules and one is already exists

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2105]
The query fails, but it should probably skip it and carry on with the rest of the modules to install

**Comment by aguillenv** [comment]
I have not been able to reproduce this. My tests cases:
- Install `aws_lambda` and then install `aws_ec2`. These 2 modules don't depend on each other and they share dependencies like `aws_vpc` or `aws_iam`. Installation of both modules works as expected.
- Install in the same query `aws_vpc` and `aws_ec2` since one is a dependency of the other. Then install `aws_lambda` too. All work.
- Install `aws_ec2`, then install `aws_ecs_fargate` and then install `aws_ecs_simplified`.
- Install `aws_ecs_fargate` and `aws_ecs_simplified` at the same time.

**Comment by aguillenv** [comment]
Ok reproduced with this:
```sql
select
  *
from
  iasql_install('aws_ecs_fargate', 'aws_ecs_fargate');
```

**Comment by aguillenv** [comment]
test also with this case to confirm once the above is solved:
```sql
select
  *
from
  iasql_install('aws_iam', 'aws_cloudwatch', 'aws_ecr', 'aws_ecs_fargate', 'aws_elb', 'aws_security_group', 'aws_vpc', 'aws_appsync', 
    'aws_ecs_fargate', 'aws_ecs_simplified', 'aws_dynamo', 'aws_ec2');
```

**Comment by aguillenv** [comment]
also, test what happens if one of the string module names has a typo
